baseURL = 'https://testing123.koord.io/'
languageCode = 'en-us'
title = 'AGRF Summit 2023'
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID

  # home page profile
  avatar = """"""
  name = 'AGRF Summit 2023'
  bio = """Africa's Food Systems Forum 2023 Summit’s theme, “Recover, Regenerate, Act: Africa’s Solutions to Food Systems Transformation,” focuses on building back better food systems and food sovereignty with youth and women at the center. The theme identifies three steps needed to achieve this transformation: Recovery, Regenerate, and Act."""


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTex math typesetting globally